#include "kernel/types.h"
#include "kernel/stat.h"
#include "user/user.h"


main(void)
{
    printf("Sleeping for 5 seconds...\n");
    
    sleep(500);   // 5 seconds (xv6: 100 ticks = 1 second)

    printf("Awake now!\n");
    
    exit(0);
}
